version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      #get from config server
      MONGO_INIT_DB_ROOT_USERNAME: admin
      MONGO_INIT_DB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db

  springboot-app:
    build:
      context: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
